### ISSUE TITLE
SyntaxError: Expected double-quoted property name in JSON at position 136 in deleteTodo Logic

### ISSUE THREAD

**Issue by ParvezMah** [ParvezMah/Backend_Full#1]
**Description**
I am encountering a SyntaxError when trying to implement the deleteTodo logic in my backend. Below is the error stack trace:

SyntaxError: Expected double-quoted property name in JSON at position 136
    at JSON.parse (<anonymous>)
    at parse (D:\03. My_Own_Projects\10_Backend_Full\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\03. My_Own_Projects\10_Backend_Full\node_modules\body-parser\lib\read.js:128:18
    at JSON.parse (<anonymous>)
    at parse (D:\03. My_Own_Projects\10_Backend_Full\node_modules\body-parser\lib\types\json.js:92:19)
    at D:\03. My_Own_Projects\10_Backend_Full\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (D:\03. My_Own_Projects\10_Backend_Full\node_modules\raw-body\index.js:238:16)
    at done (D:\03. My_Own_Projects\10_Backend_Full\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\03. My_Own_Projects\10_Backend_Full\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:514:28)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Steps to Reproduce**
Set up the deleteTodo logic in the backend using Express.js and body-parser.
Send a DELETE request to the endpoint with the ID in the request body:
json
Copy code
{ id: '123' }
Observe the error during JSON parsing.

**Expected Behavior**
The server should handle the request gracefully and delete the specified Todo item or return an appropriate error message if the Todo does not exist.

**Actual Behavior**
A SyntaxError occurs, and the server logs the stack trace mentioned above.

**Possible Cause**
JSON properties are not wrapped in double quotes.
DELETE requests typically do not include a body; the server may be misconfigured to expect one.
The client might be sending malformed JSON or not setting the Content-Type header to application/json.

**Comment by ParvezMah** [comment]
![BackendFullStack_DeletoTodo_error](https://github.com/user-attachments/assets/68d304a0-e7f3-4a2c-9cac-2cacb015a632)
